// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR-YnB3OOvyhz91IeF8JDQ45474MzeaUY',
    appId: '1:534792271600:web:b9af28e0d6ad8c35447435',
    messagingSenderId: '534792271600',
    projectId: 'se-rental-app',
    authDomain: 'se-rental-app.firebaseapp.com',
    storageBucket: 'se-rental-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqNNAouA2yR9wc8iJboujFhgpF0oAOs-Y',
    appId: '1:534792271600:android:9b67f76c6c53d257447435',
    messagingSenderId: '534792271600',
    projectId: 'se-rental-app',
    storageBucket: 'se-rental-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHhOxO6VaOGLpc9mL1yVFeyVwr8eHtlg',
    appId: '1:534792271600:ios:36bec9b1544ab0cb447435',
    messagingSenderId: '534792271600',
    projectId: 'se-rental-app',
    storageBucket: 'se-rental-app.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );
}
